---
- hosts: all
  become: yes
  vars:
    - user:    'vagrant'
    - pg_conf: '/var/lib/pgsql/data/postgresql.conf'
    - pg_hba:  '/var/lib/pgsql/data/pg_hba.conf'
    - gitrepo: 'https://github.com/Lab-Brat/flask_masque.git'
    - git_app: '/home/{{ user }}/infra-forms'
    - bashrc:  '/home/{{ user }}/.bashrc'
    - dumps:   '/home/{{ user }}/dumps'
    - samples: '/home/{{ user }}/infra-forms/samples/add_entries.sh'
    - env_app: 'app.py'
    - env_mod: 'development'
    - db_port: 5433
    - db_user: 'labbrat'
    - db_name: 'db_infra_forms'
    - db_pass: 'password'

  tasks:
  - block:
      - name: install pip , git and PostgreSQL
        dnf:
          name: '{{ item }}'
          state: present
        with_items:
          - python3-pip
          - python3-psycopg2
          - git
          - postgresql
          - postgresql-server

      - name: install Python libraries
        pip: 
          name: "{{ item }}"
        with_items:
          - Flask
          - flask-migrate
          - SQLAlchemy
          - psycopg2

      - name: clone github repository with forms app
        ansible.builtin.git:
          repo: '{{ gitrepo }}'
          dest: '{{ git_app }}'
          clone: yes
        become: false

      - name: Create and folder for database dumps
        file:
          state: directory
          path: "{{ dumps }}"

      - name: add FLASK_APP environmental variable
        ansible.builtin.lineinfile:
          path: "{{ bashrc }}"
          line: "export FLASK_APP={{ env_app }}"

      - name: add FLASK_ENV environmental variable
        ansible.builtin.lineinfile:
          path: "{{ bashrc }}"
          line: "export FLASK_ENV={{ env_mod }}"
      
      - name: change ownership of the app folder
        ansible.builtin.file:
          path: '{{ git_app }}'
          state: directory
          recurse: yes
          owner: "{{ user }}"
          group: "{{ user }}"

      - name: find out if PostgreSQL is initialized
        ansible.builtin.stat:
          path: "{{ pg_hba }}"
        register: postgres_data 

      - name: initialize postgres
        shell: "/usr/bin/postgresql-setup --initdb"
        when: not postgres_data.stat.exists

      - name: start PostgreSQL server
        service: name='postgresql' state=started enabled=yes

      - name: change postgresql.conf
        ansible.builtin.lineinfile:
          path: '{{ pg_conf }}'
          regexp: "listen_addresses = 'localhost'"
          line: "listen_addresses = '*'"

      - name: change pg_hba.conf - change port
        ansible.builtin.lineinfile:
          path: '{{ pg_conf }}'
          regexp: "port = 5432"
          line: "port = {{ db_port }}"

      - name: change pg_hba.conf
        ansible.builtin.lineinfile:
          path: '{{ pg_hba }}'
          regexp: "host    all             all             127.0.0.1/32            ident"
          line: "host    all             all             127.0.0.1/32            trust"

      - name: remove app database if it exists
        postgresql_db:
          state: absent
          name: "{{ db_name }}"
          port: "{{ db_port }}"
        become: yes
        become_user: postgres

      - name: create app database
        postgresql_db:
          state: present
          name: "{{ db_name }}"
          port: "{{ db_port }}"
        become: yes
        become_user: postgres
  
      - name: create db user
        postgresql_user:
          state: present
          name: "{{ db_user }}"
          password: "{{ db_pass }}"
          port: "{{ db_port }}"
        become: yes
        become_user: postgres
  
      - name: grant db user access to app db
        postgresql_privs:
          type: database
          database: "{{ db_name }}"
          roles: "{{ db_user }}"
          grant_option: no
          privs: all
          port: "{{ db_port }}"
        become: yes
        become_user: postgres

      - name: allow port 5000 in firewalld 
        ansible.posix.firewalld:
          port: 5000/tcp
          permanent: yes
          state: enabled

      - name: delete migrations folder if exists
        file:
          state: absent
          path: "{{ git_app }}/migrations"

      - name: initialize the database
        command: "flask db init"
        args:
          chdir: "{{ git_app }}"
        become: false

      - name: migrate the database
        command: "flask db migrate"
        args:
          chdir: "{{ git_app }}"
        become: false

      - name: upgrade the database
        command: "flask db upgrade"
        args:
          chdir: "{{ git_app }}"
        become: false

      - name: add sample data
        command: "sh {{ samples }}"
        become: false
        
    when: ansible_distribution == 'AlmaLinux'

