---
- hosts: all
  become: yes
  vars:
    - src_jenkins: '/var/jenkins'
    - src_compose: '/home/labbrat/ansible/configs/docker-compose.yaml'

  tasks:
  - block: # install Jenkins in a container on Fedora
      - name: install docker-compose
        dnf:
          name: 'docker-compose'
          state: present
      
      - name: create directory for compose file if it doesn't exist
        ansible.builtin.file:
          path: "{{ src_jenkins }}"
          state: directory
          mode: '0755'

      - name: copy docker-compose file to remote host
        ansible.builtin.copy:
          src: "{{ src_compose }}" 
          dest: "{{ src_jenkins }}"
          mode: '0644'

      - name: launch docker-compose
        community.docker.docker_compose:
          project_src: "{{ src_jenkins }}"
        register: output
  
      - ansible.builtin.debug:
          var: output

    when: ansible_distribution == 'Fedora'

