---
- hosts: all
  become: yes
  vars:
    - bashrc: '/home/vagrant/.bashrc'

  tasks:
  - block: # install modern linux commands on Linux
      - name: install commands with package manager
        dnf:
          name: '{{ item }}'
          state: present
        with_items:
          - lsd
          - bat

      - name: ensure that custom alias information line is there
        lineinfile:
          name: "{{ bashrc }}"
          line: "######## Custom Aliases Created By Ansible ########"
          state: present
        check_mode: yes
        register: custom_alias_notify

      - name: add alias title
        ansible.builtin.lineinfile:
          path: "{{ bashrc }}"
          line: "\n######## Custom Aliases Created By Ansible ########"
        when: custom_alias_notify is changed

      - name: add alias to lsd to bashrc
        ansible.builtin.lineinfile:
          path: "{{ bashrc }}"
          line: "alias ls=lsd"
   
      - name: add alias to bat
        ansible.builtin.lineinfile:
          path: "{{ bashrc }}"
          line: "alias cat=bat"

    when: ansible_distribution == 'Fedora'

